# Generated by Django 4.0.3 on 2022-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identify_number',
            field=models.CharField(default='5430182735', max_length=10),
        ),
    ]
