# Generated by Django 4.0.3 on 2022-04-18 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.IntegerField(default=operations.models.transfer_code)),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('KGS', 'KGZ')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('KGS', 'KGZ')], default='KGZ', max_length=3)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.IntegerField(default=operations.models.transfer_code)),
                ('salary', models.PositiveIntegerField()),
                ('pledge', models.CharField(blank=True, choices=[('mortgage', 'mortgage'), ('consumer', 'consumer')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_long', models.DateField()),
                ('date_taking', models.DateField(auto_now_add=True)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_payment', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
