# Generated by Django 4.0.3 on 2022-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='checkk',
            field=models.BooleanField(default=False),
        ),
    ]
