# Generated by Django 4.0.3 on 2022-04-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_credit_checkk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='checkk',
        ),
        migrations.AddField(
            model_name='credit',
            name='every_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
