# Generated by Django 4.0.3 on 2022-04-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_credit_checkk_credit_every_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_long',
            field=models.DateField(auto_now_add=True),
        ),
    ]
