# Generated by Django 4.0.3 on 2022-04-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_credit_credit_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='notices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_long',
            field=models.DateField(),
        ),
    ]
